ALTER TABLE Users
DROP CONSTRAINT PK__Users__3214EC0767A1681A

ALTER TABLE Users
ADD CONSTRAINT PK_Id_And_Username PRIMARY KEY (Id, [Username]);

ALTER TABLE Users
ADD CONSTRAINT DEF_LOGIN_DATE DEFAULT GETDATE() FOR LastLoginTime

ALTER Table Users
DROP CONSTRAINT PK_Id_And_Username

ALTER TABLE Users
ADD CONSTRAINT PK_ID PRIMARY KEY (Id)

ALTER TABLE Users
ADD CONSTRAINT TREE_SYMBOLS_MIN CHECK (LEN(Username) >= 4)
